apiVersion: v1
kind: Pod
metadata:
  name: nginx #pod name
  labels: #for grouping purposes
    app: nginx
    tier: front-end
spec:
  containers:
    - name: nginx
      image: nginx #docker hub image name
