apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx #pod name
      labels: #for grouping purposes
        app: nginx
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx #docker hub image name
  replicas: 3
  selector:
    matchLabels:
      tier: front-end